version: "3.9"
services:
  deep-journalist:
    build:
      context: .
      dockerfile: Dockerfile
    image: deep-journalist
    container_name: deep-journalist-app
    environment:
      - ACCESS_PASSWORD=${ACCESS_PASSWORD}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - API_PROXY_BASE_URL=${API_PROXY_BASE_URL}
      - HEAD_SCRIPTS=${HEAD_SCRIPTS}
    ports:
      - "3000:3000"
