version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend/nextjs
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
    depends_on:
      - api

  e2e:
    build:
      context: ./frontend/nextjs
      dockerfile: Dockerfile.e2e
    environment:
      - PLAYWRIGHT_TEST_BASE_URL=http://frontend:3000
      - CI=1
    depends_on:
      - frontend
      - api

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 